-- noinspection SqlDialectInspectionForFile

CREATE TABLE TESTS2
(
   CUSTOMER_ID     VARCHAR2 (255),
   NAME            VARCHAR2 (100),
   SUBSCRIPTION    VARCHAR2 (255),
   CREATED_DATE    DATE,
   CREATED_BY      VARCHAR2 (255),
   MODIFIED_DATE   TIMESTAMP (6),
   MODIFIED_BY     VARCHAR2 (255)
);

exit;